# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#3c3836" }

# Find
find_keyword = { fg = "#d79921", bold = true, italic = true, underline = true }
find_position = { fg = "#98971a", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "#98971a", bg = "#98971a" }
marker_cut = { fg = "#cc241d", bg = "#cc241d" }
marker_marked = { fg = "#3c3836", bg = "#3c3836" }
marker_selected = { fg = "#d79921", bg = "#d79921" }

# Count
count_copied = { fg = "#FAF5D7", bg = "#98971a" }
count_cut = { fg = "#FAF5D7", bg = "#cc241d" }
count_selected = { fg = "#FAF5D7", bg = "#d79921" }

# Border
border_symbol = "│"
border_style = { fg = "#a89984" }

# : }}}


# : Tabs {{{

[tabs]
active = { fg = "#FAF5D7", bg = "#689d6a", bold = true }
inactive = { fg = "#689d6a", bg = "#fbf7ef" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#FAF5D7", bg = "#689d6a", bold = true }
normal_alt = { fg = "#689d6a", bg = "#fbf7ef" }

# Select mode
select_main = { fg = "#FAF5D7", bg = "#3c3836", bold = true }
select_alt = { fg = "#3c3836", bg = "#fbf7ef" }

# Unset mode
unset_main = { fg = "#FAF5D7", bg = "#98971a", bold = true }
unset_alt = { fg = "#98971a", bg = "#fbf7ef" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep = { fg = "#623625" }
perm_type = { fg = "#458588" }
perm_read = { fg = "#d79921" }
perm_write = { fg = "#cc241d" }
perm_exec = { fg = "#98971a" }

# Progress
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#98971a", bg = "#f3e9d2" }
progress_error = { fg = "#d79921", bg = "#cc241d" }

# : }}}


# : Pick {{{

[pick]
border = { fg = "#689d6a" }
active = { fg = "#98971a", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#689d6a" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#689d6a" }

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#689d6a" }
title = {}
hovered = { fg = "#98971a", bold = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#fbf7ef" }
cand = { fg = "#3c3836" }
rest = { fg = "#371b11" }
desc = { fg = "#98971a" }
separator = "  "
separator_style = { fg = "#eadbb4" }

# : }}}


# : Help {{{

[help]
on = { fg = "#3c3836" }
run = { fg = "#98971a" }
hovered = { reversed = true, bold = true }
footer = { fg = "#fbf7ef", bg = "#7c6f64" }

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#689d6a" }
title = { fg = "#689d6a" }
tbl_col = { fg = "#3c3836" }
tbl_cell = { fg = "#98971a", bg = "#f3e9d2" }

# : }}}


# : Notification {{{

[notify]
title_info = { fg = "#98971a" }
title_warn = { fg = "#d79921" }
title_error = { fg = "#cc241d" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Image
  { mime = "image/*", fg = "#3c3836" },
  # Media
  { mime = "{audio,video}/*", fg = "#d79921" },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#98971a" },
  # Document
  { mime = "application/{pdf,doc,rtf}", fg = "#98971a" },
  # Virtual file system
  { mime = "vfs/{absent,stale}", fg = "#371b11" },
  # Fallback
  { url = "*", fg = "#7c6f64" },
  { url = "*/", fg = "#689d6a" },
]

# : }}}

[icon]

dirs = [
  { name = ".config", text = "", fg = "#98971a" },
  { name = ".git", text = "", fg = "#3c3836" },
  { name = ".github", text = "", fg = "#689d6a" },
  { name = ".npm", text = "", fg = "#689d6a" },
  { name = "Desktop", text = "", fg = "#3c3836" },
  { name = "Development", text = "", fg = "#3c3836" },
  { name = "Documents", text = "", fg = "#3c3836" },
  { name = "Downloads", text = "", fg = "#3c3836" },
  { name = "Library", text = "", fg = "#3c3836" },
  { name = "Movies", text = "", fg = "#3c3836" },
  { name = "Music", text = "", fg = "#3c3836" },
  { name = "Pictures", text = "", fg = "#3c3836" },
  { name = "Public", text = "", fg = "#3c3836" },
  { name = "Videos", text = "", fg = "#3c3836" },
]
conds = [
  # Special files
  { if = "orphan", text = "", fg = "#7c6f64" },
  { if = "link", text = "", fg = "#623625" },
  { if = "block", text = "", fg = "#98971a" },
  { if = "char", text = "", fg = "#98971a" },
  { if = "fifo", text = "", fg = "#98971a" },
  { if = "sock", text = "", fg = "#98971a" },
  { if = "sticky", text = "", fg = "#98971a" },
  { if = "dummy", text = "", fg = "#cc241d" },

  # Fallback
  { if = "dir", text = "", fg = "#458588" },
  { if = "exec", text = "", fg = "#98971a" },
  { if = "!dir", text = "", fg = "#7c6f64" },
]
