[flavor]
dark = "gruvbox-dark"
light = "gruvbox-light"

[indicator]
padding = { open = "▐", close = "▌" }

[status]
overall = {}
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

[tabs]
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }
